"""
data_loader.py  --  TIP ESG Platform
======================================
Loads consolidated data and maps every field to TemplateInputs field names.

Search order for source data:
  1. data_storage/raw/ESG_MASTER_WIDE_ALL_COMPANIES_2009_2023.xlsx  (generated by build_esg_master.py)
  2. data_storage/raw/CONSOLIDATED_DUMMY_2009_2023.xlsx             (original source)
  3. data_storage/consolidated/CONSOLIDATED_DUMMY_2009_2023.xlsx    (legacy location)
  4. CONSOLIDATED_DUMMY_2009_2023.xlsx                              (project root fallback)
  5. CSV fallbacks
"""
from pathlib import Path
import pandas as pd

# ── Source file search order ───────────────────────────────────────────────────
_XLSX_CANDIDATES = [
    # Primary: master wide file generated by build_esg_master.py (raw folder)
    (Path("data_storage/raw/ESG_MASTER_WIDE_ALL_COMPANIES_2009_2023.xlsx"), "All_Companies"),
    # Secondary: original consolidated dummy (raw folder)
    (Path("data_storage/raw/CONSOLIDATED_DUMMY_2009_2023.xlsx"),            "Raw Dummy data"),
    # Legacy: consolidated folder (kept for backward compatibility)
    (Path("data_storage/consolidated/CONSOLIDATED_DUMMY_2009_2023.xlsx"),   "Raw Dummy data"),
    # Root fallback
    (Path("CONSOLIDATED_DUMMY_2009_2023.xlsx"),                             "Raw Dummy data"),
]

_CSV_CANDIDATES = [
    Path("data_storage/raw/ESG_MASTER_WIDE_ALL_COMPANIES_2009_2023.csv"),
    Path("data_storage/consolidated/consolidated_benchmarking.csv"),
    Path("consolidated_benchmarking.csv"),
]

# ── Field mapping: Row_Label (long format) -> TemplateInputs field name ────────
# Used when loading from the original long-format consolidated Excel.
# Not needed when loading from the wide master CSV (columns already named correctly).
LABEL_TO_FIELD = {
    "Total no. of sites":                              "total_sites",
    "ISO 14001 sites":                                 "iso_sites",
    "Production":                                      "production",
    "Water intake":                                    "water_withdrawals",
    "Renewable Electricity Purchased":                 "renew_elec_purchased",
    "Non-Renewable Electricity Purchased":             "nonrenew_elec_purchased",
    "Self-generated AND consumed electricity on-site": "self_gen_elec",
    "Purchased Steam":                                 "purchased_steam",
    "Sold Electricity":                                "sold_electricity",
    "Sold Steam":                                      "sold_steam",
    "Natural Gas":                                     "nat_gas",
    "Coal":                                            "coal_sub",
    "Propane":                                         "propane",
    "Fuel Oil":                                        "fuel_oil_heavy_a",
    "Diesel":                                          "diesel",
    "Petrol":                                          "petrol",
    "Biomass":                                         "biomass",
    "Waste tires":                                     "waste_tires_mt",
    "LPG":                                             "lpg",
    "Other":                                           "other_fuels",
    "Total amount of waste ":                          "waste_total",
    "Amount of waste sent to recovery":                "waste_recovery",
}

KPI_LABELS = {
    "Water intake - KPI":     "water_kpi",
    "Total energy - KPI":     "energy_kpi",
    "Total CO2 - KPI":        "co2_kpi",
    "% certified sites":      "iso_pct",
    "Waste intensity - KPI ": "waste_kpi",
}

BENCH_LABELS = {
    "Total energy - KPI": "energy_kpi",
    "Total CO2 - KPI":    "co2_kpi",
    "Water intake - KPI": "water_kpi",
}

# Wide-format column names -> TemplateInputs field names
# Every column from the master CSV that maps to a TemplateInputs field is listed here.
# Columns NOT in this dict (e.g. formulated KPIs like "Total energy", "Total CO2")
# are intentionally excluded -- they are outputs, not inputs.
WIDE_COL_TO_FIELD = {
    # ISO
    "Total no. of sites":                              "total_sites",
    "ISO 14001 sites":                                 "iso_sites",
    # Production
    "Production":                                      "production",
    # Water
    "Water intake":                                    "water_withdrawals",
    # Electricity
    "Total Electricity":                               "renew_elec_purchased",   # approx -- split below not available
    "Renewable Electricity Purchased":                 "renew_elec_purchased",
    "Non-Renewable Electricity Purchased":             "nonrenew_elec_purchased",
    "Self-generated AND consumed electricity on-site": "self_gen_elec",
    "Purchased Steam":                                 "purchased_steam",
    "Sold Electricity":                                "sold_electricity",
    "Sold Steam":                                      "sold_steam",
    # Fuels
    "Natural Gas":                                     "nat_gas",
    "Coal":                                            "coal_sub",
    "Propane":                                         "propane",
    "Fuel Oil":                                        "fuel_oil_heavy_a",
    "Diesel":                                          "diesel",
    "Petrol":                                          "petrol",
    "Biomass":                                         "biomass",
    "Waste tires":                                     "waste_tires_mt",
    "LPG":                                             "lpg",
    "Other":                                           "other_fuels",
    # Waste
    "Total amount of waste":                           "waste_total",
    "Amount of waste sent to recovery":                "waste_recovery",
}

# Valid TemplateInputs field names -- used to filter out formulated columns
# before passing **fields to TemplateInputs(). Keeps only input fields.
TEMPLATE_INPUT_FIELDS = {
    "total_sites", "iso_sites", "production", "water_withdrawals",
    "renew_elec_purchased", "nonrenew_elec_purchased", "self_gen_elec",
    "purchased_steam", "sold_electricity", "sold_steam",
    "nat_gas", "coal_sub", "propane", "fuel_oil_heavy_a",
    "diesel", "petrol", "biomass", "waste_tires_mt", "lpg", "other_fuels",
    "co2_scope2_steam", "waste_total", "waste_recovery",
}


def _is_wide_format(df: pd.DataFrame) -> bool:
    """Returns True if the DataFrame is already in wide (Company x Year) format."""
    return "Company" in df.columns and "Year" in df.columns and "Row_Label" not in df.columns


def load_consolidated() -> pd.DataFrame:
    """
    Load source data. Returns a cleaned DataFrame.
    Wide-format files (master CSV/Excel) are returned as-is.
    Long-format files (original consolidated Excel) are returned in long format
    for backward compatibility -- get_company_hist() handles both.
    """
    for path, sheet in _XLSX_CANDIDATES:
        if path.exists():
            try:
                df = pd.read_excel(path, sheet_name=sheet, header=0)
                df.columns = [str(c).strip() for c in df.columns]
                df["Year"] = pd.to_numeric(df["Year"], errors="coerce").astype("Int64")
                df = df.dropna(subset=["Year"])

                if _is_wide_format(df):
                    # Wide master format -- numeric coercion on all non-id columns
                    for col in df.columns:
                        if col not in ("Company", "Year"):
                            df[col] = pd.to_numeric(df[col], errors="coerce")
                    print(f"[data_loader] Loaded WIDE format: {path.name} -- {len(df)} rows")
                else:
                    # Long format
                    df["Data"] = pd.to_numeric(df["Data"], errors="coerce")
                    df = df.dropna(subset=["Row_Label"])
                    df["Row_Label"] = df["Row_Label"].astype(str).str.strip()
                    print(f"[data_loader] Loaded LONG format: {path.name} (sheet: {sheet}) -- {len(df)} rows")

                return df
            except Exception as e:
                print(f"[data_loader] Could not load {path.name}: {e}")

    for path in _CSV_CANDIDATES:
        if path.exists():
            try:
                df = pd.read_csv(path)
                df.columns = [str(c).strip() for c in df.columns]
                df["Year"] = pd.to_numeric(df["Year"], errors="coerce").astype("Int64")
                df = df.dropna(subset=["Year"])

                if _is_wide_format(df):
                    for col in df.columns:
                        if col not in ("Company", "Year"):
                            df[col] = pd.to_numeric(df[col], errors="coerce")
                    print(f"[data_loader] Loaded WIDE CSV: {path} -- {len(df)} rows")
                else:
                    df["Data"] = pd.to_numeric(df["Data"], errors="coerce")
                    df = df.dropna(subset=["Row_Label"])
                    df["Row_Label"] = df["Row_Label"].astype(str).str.strip()
                    print(f"[data_loader] Loaded LONG CSV: {path} -- {len(df)} rows")

                return df
            except Exception as e:
                print(f"[data_loader] CSV error ({path}): {e}")

    print("[data_loader] WARNING: No data file found. Run build_esg_master.py first.")
    return pd.DataFrame()


def get_companies(df: pd.DataFrame) -> list:
    if df.empty:
        return []
    return sorted(df["Company"].dropna().unique().tolist())


def get_years(df: pd.DataFrame, company: str = None) -> list:
    if df.empty:
        return []
    sub = df[df["Company"] == company] if company else df
    return sorted(sub["Year"].dropna().unique().astype(int).tolist())


def get_company_hist(df: pd.DataFrame, company: str) -> dict:
    """
    Returns {field: {year: value}} for all INPUT fields of a company.
    Keys are always valid TemplateInputs field names.
    Formulated columns (Total energy, Total CO2, KPIs) are excluded.
    Handles both wide and long format DataFrames.
    """
    if df.empty:
        return {}

    comp_df = df[df["Company"] == company]

    if _is_wide_format(df):
        result = {}
        for col in comp_df.columns:
            if col in ("Company", "Year"):
                continue
            # Map wide CSV column name -> TemplateInputs field name
            field = WIDE_COL_TO_FIELD.get(col, col)
            # Only keep valid TemplateInputs input fields -- skip formulated outputs
            if field not in TEMPLATE_INPUT_FIELDS:
                continue
            rows = comp_df[["Year", col]].dropna(subset=[col])
            if not rows.empty:
                result[field] = {int(yr): float(val)
                                 for yr, val in zip(rows["Year"], rows[col])
                                 if pd.notna(val)}
        return result

    # Long format: one row per KPI per year
    result = {}
    for label, field in LABEL_TO_FIELD.items():
        if field not in TEMPLATE_INPUT_FIELDS:
            continue
        rows = comp_df[comp_df["Row_Label"] == label.strip()][["Year", "Data"]].dropna()
        if not rows.empty:
            result[field] = {int(yr): float(val)
                             for yr, val in zip(rows["Year"], rows["Data"])
                             if pd.notna(val)}
    return result


def get_step_data(company_hist: dict, year: int) -> dict:
    """Returns {field: value} for a given year -- pre-fills stepper inputs."""
    return {f: float(ym[year])
            for f, ym in company_hist.items()
            if year in ym and pd.notna(ym[year])}


def get_hist_raw(company_hist: dict, years: list) -> dict:
    """Returns {field: [value_per_year]} -- populates historical columns in the template table."""
    hist = {}
    for field, ym in company_hist.items():
        vals = [float(ym.get(yr, 0.0)) for yr in years]
        if any(v != 0.0 for v in vals):
            hist[field] = vals
    return hist


def get_kpi_hints(df: pd.DataFrame, company: str, year: int) -> dict:
    """Returns prior-year KPIs as {kpi_name: value} for reference hints in the stepper."""
    if df.empty:
        return {}

    if _is_wide_format(df):
        row = df[(df["Company"] == company) & (df["Year"] == year)]
        if row.empty:
            return {}
        hints = {}
        kpi_map = {
            "Total energy - KPI":  "energy_kpi",
            "Total CO2 - KPI":     "co2_kpi",
            "Water intake - KPI":  "water_kpi",
            "% certified sites":   "iso_pct",
        }
        # Wide format uses the column names directly
        wide_kpi_map = {
            "Total energy - KPI":  "energy_kpi",
            "Total CO2 - KPI":     "co2_kpi",
            "Water intake - KPI":  "water_kpi",
            "% certified sites":   "iso_pct",
        }
        for col, kpi in wide_kpi_map.items():
            if col in row.columns and pd.notna(row[col].values[0]):
                hints[kpi] = float(row[col].values[0])
        return hints

    # Long format
    comp_yr = df[(df["Company"] == company) & (df["Year"] == year)]
    hints = {}
    for label, kpi in KPI_LABELS.items():
        rows = comp_yr[comp_yr["Row_Label"] == label.strip()]["Data"].dropna()
        if not rows.empty:
            hints[kpi] = float(rows.iloc[0])
    return hints


def get_benchmark_kpis(df: pd.DataFrame, year: int) -> pd.DataFrame:
    """
    Returns a DataFrame with [Company, energy_kpi, co2_kpi, water_kpi]
    for all companies in a given year -- used to compute quartile bands.
    """
    if df.empty:
        return pd.DataFrame()

    year_df = df[df["Year"] == year]

    if _is_wide_format(df):
        cols = {"Company": "Company"}
        kpi_col_map = {
            "Total energy - KPI": "energy_kpi",
            "Total CO2 - KPI":    "co2_kpi",
            "Water intake - KPI": "water_kpi",
        }
        available = {k: v for k, v in kpi_col_map.items() if k in year_df.columns}
        if not available:
            return pd.DataFrame()
        result = year_df[["Company"] + list(available.keys())].copy()
        result = result.rename(columns=available)
        return result.reset_index(drop=True)

    # Long format
    frames = []
    for label, col in BENCH_LABELS.items():
        rows = year_df[year_df["Row_Label"] == label.strip()][["Company", "Data"]].copy()
        rows = rows.rename(columns={"Data": col})
        if not rows.empty:
            frames.append(rows.set_index("Company")[col])
    return pd.concat(frames, axis=1).reset_index() if frames else pd.DataFrame()


def improvement_since(company_hist: dict, field: str, base_year: int, end_year: int):
    """% change from base_year to end_year for a given field. Returns None if unavailable."""
    ym = company_hist.get(field, {})
    base = ym.get(base_year)
    end  = ym.get(end_year)
    if base and end and base != 0:
        return (end - base) / abs(base) * 100
    return None


def company_trend(df: pd.DataFrame, company: str, row_label: str) -> "pd.Series":
    """Returns a Year-indexed Series of values for a given company and KPI label."""
    if df.empty:
        return pd.Series(dtype=float)
    if _is_wide_format(df):
        col = WIDE_COL_TO_FIELD.get(row_label, row_label)
        if col not in df.columns:
            return pd.Series(dtype=float)
        mask = df["Company"] == company
        return df[mask].set_index("Year")[col].sort_index()
    mask = (df["Company"] == company) & (df["Row_Label"] == row_label.strip())
    return df[mask].set_index("Year")["Data"].sort_index()


def load_sector_aggregated() -> "pd.DataFrame":
    """
    Load the pre-aggregated sector-level CSV (generated by build_esg_master.py).
    Returns an empty DataFrame if not found.
    """
    candidates = [
        Path("data_storage/raw/ESG_SECTOR_AGGREGATED_2009_2023.csv"),
        Path("data_storage/consolidated/ESG_SECTOR_AGGREGATED_2009_2023.csv"),
    ]
    for path in candidates:
        if path.exists():
            try:
                df = pd.read_csv(path)
                df["Year"] = df["Year"].astype(int)
                print(f"[data_loader] Loaded sector aggregation: {path}")
                return df
            except Exception as e:
                print(f"[data_loader] Sector CSV error: {e}")
    return pd.DataFrame()